### ISSUE TITLE
Command line option

### ISSUE THREAD

**Issue by jrett** [theoolee/vscode-reader-mode#4]
I often start vscode via the command line from wsl and sometimes I just want to start it in readonly mode. Can a command line flag be added so that when it's specified then no edits can be made?

**Comment by mossgowild** [comment]
There isn't an official extension API that supports this function, but you can use the profile feature of vscode to do this. Just create a profile with configuration:
```json
{
  "reader-mode.auto.glob": ["**"]
}
```
And open vscode from the terminal by `code --profile <profileName>`.
