### ISSUE TITLE
reader-mode.toggleWorkspace 不起作用了

### ISSUE THREAD

**Issue by tobey11799** [theoolee/vscode-reader-mode#6]
reader-mode.toggleWorkspace don't work anymore.

**Comment by mossgowild** [comment]
This extension is deprecated now, please use the [official readonly mode](https://code.visualstudio.com/updates/v1_79#_readonly-mode).

**Comment by tobey11799** [comment]
I'll check it. thanks for your information and reply, I appreciate that.
